apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-site
spec:
  selector:
    matchLabels:
      app: personal
  replicas: 3
  template:
    metadata:
      labels:
        app: personal
    spec:
      containers:
        - name: personal-site
          args:
            - sleep
            - "1000000"
          image: "gcr.io/personal-site-206007/personal-view"

