apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      app: metrics
      department: sales
  replicas: 3
  template:
    metadata:
      labels:
        app: metrics
        department: sales
    spec:
      containers:
        - name: personal-site
          args:
            - sleep
            - "1000000"
          image: "gcr.io/personal-site-206007/personal-view"

